var express = require('express');
var path = require('path');
var cookieParser = require('cookie-parser');
var logger = require('morgan');

var indexRouter = require('./routes/index');
var usersRouter = require('./routes/users');
var cors = require('cors');
var loginrouter = require('./routes/login');
var districtview = require('./routes/districtview');
var deletedistrict = require('./routes/deletedistrict');
var addlocation = require('./routes/addlocation');
var locationview = require('./routes/locationview');
var locationdelete = require('./routes/locationdelete');
var locationedit = require('./routes/locationedit');
var addcategory = require('./routes/addcategory');
var upload = require('./routes/upload');
var categoryview = require('./routes/categoryview');
var categorydelete = require('./routes/categorydelete');
var locationbyid = require('./routes/locationbyid');
var categorybyid = require('./routes/getcategory');
var adddesigner = require('./routes/adddesigner');
var categoryedit = require('./routes/categoryedit');
var designerview = require('./routes/designerview');
var acceptdesigner = require('./routes/acceptdesigner');
var rejectdesigner = require('./routes/rejectdesigner');
var previousworkview = require('./routes/previousworkview');
var addpreviouswork = require('./routes/addpreviouswork');
var deletepreviouswork = require('./routes/deletepreviouswork');
var getpreviousworkbyid = require('./routes/getpreviousworkbyid');
var updatepreviouswork = require('./routes/updatepreviouswork');
var addcustomer = require('./routes/addcustomer');
var addpost = require('./routes/addpost');
var postview = require('./routes/postview');
var addpostreplay = require('./routes/addpostreplay');
var postreplayview = require('./routes/postreplayview');
var designerrequestview = require('./routes/designerrequestview');
var acceptrequest = require('./routes/acceptrequest');
var rejectrequest = require('./routes/rejectrequest');
var customerpostview = require('./routes/customerpostview');
var approvedwork = require('./routes/approvedwork');
var addCommittedWork = require('./routes/addCommittedWork');
var getcustomerbycode = require('./routes/getcustomerbycode');
var getAcceptedPostreplay = require('./routes/getAcceptedPostreplay');
var committedworkview = require('./routes/committedWorkView');
var addCommittedWorkprograss = require('./routes/addCommittedWorkProgress');
var getcommittedworkbyid = require('./routes/getcommittedworkbyid');
var addpayment = require('./routes/addpayment');
var paymentbalance = require('./routes/paymentbalance');
var report = require('./routes/Report');
var yearlyPaymentReport = require('./routes/yearlyPaymentReport');
var designerworkstats = require('./routes/designerworkstats');
var designerprofile = require('./routes/designerprofile');
var updatedesignerprofile = require('./routes/updatedesignerprofile');
var checkusername = require('./routes/checkusername');
var customerprofile = require('./routes/customerprofile');
var updatecustomerprofile = require('./routes/updatecustomerprofile');
var getCustomersByDesigner = require('./routes/getCustomersByDesigner');
var sendotp = require('./routes/sendotp');
var verifyotp = require('./routes/verifyotp');
var resetpassword = require('./routes/resetpassword');
var admindashboard = require('./routes/admindashboard');
var adminCommission = require('./routes/adminCommission');
var addofflinework = require('./routes/addofflinework');
var app = express();


app.use(logger('dev'));
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));

global.__basedir = path.resolve(path.dirname(''));  //new

app.use('/', indexRouter);
app.use('/users', usersRouter);
app.use(cors());
app.use('/login', loginrouter);
app.use('/districtview', districtview);
app.use('/deletedistrict', deletedistrict);
app.use('/addlocation', addlocation);
app.use('/locationview', locationview);
app.use('/locationdelete', locationdelete);
app.use('/locationedit', locationedit);
app.use('/addcategory', addcategory);
app.use('/upload', upload);
app.use('/categoryview', categoryview);
app.use('/categorydelete', categorydelete);
app.use('/locationbyid', locationbyid);
app.use('/categorybyid', categorybyid);
app.use('/getcategory', categorybyid);
app.use('/categoryedit', categoryedit);
app.use('/adddesigner', adddesigner);
app.use('/designerview', designerview);
app.use('/acceptdesigner', acceptdesigner);
app.use('/rejectdesigner', rejectdesigner);
app.use('/previousworkview', previousworkview);
app.use('/addpreviouswork', addpreviouswork);
app.use('/deletepreviouswork', deletepreviouswork);
app.use('/getpreviousworkbyid', getpreviousworkbyid);
app.use('/updatepreviouswork', updatepreviouswork);
app.use('/addcustomer', addcustomer);
app.use('/addpost', addpost);
app.use('/postview', postview);
app.use('/addpostreplay', addpostreplay);
app.use('/postreplayview', postreplayview);
app.use('/designerrequestview', designerrequestview);
app.use('/acceptrequest', acceptrequest);
app.use('/rejectrequest', rejectrequest);
app.use('/customerpostview', customerpostview);
app.use('/approvedwork', approvedwork);
app.use('/addCommittedWork', addCommittedWork);
app.use('/getcustomerbycode', getcustomerbycode);
app.use('/customerbycode', getcustomerbycode);
app.use('/acceptedpostreplay', getAcceptedPostreplay);
app.use('/committedworkview', committedworkview);
app.use('/addcommittedworkprogress', addCommittedWorkprograss);
app.use('/getcommittedworkbyid', getcommittedworkbyid);
app.use('/addpayment', addpayment);
app.use('/paymentbalance', paymentbalance);
app.use('/report', report);
app.use('/yearlypaymentreport', yearlyPaymentReport);
app.use('/designerworkstats', designerworkstats);
app.use('/designerprofile', designerprofile);
app.use('/updatedesignerprofile', updatedesignerprofile);
app.use('/checkusername', checkusername);
app.use('/customerprofile', customerprofile);
app.use('/updatecustomerprofile', updatecustomerprofile);
app.use('/getcustomersbydesigner', getCustomersByDesigner);
app.use('/sendotp', sendotp);
app.use('/verifyotp', verifyotp);
app.use('/resetpassword', resetpassword);
app.use('/admindashboard', admindashboard);
app.use('/admincommission', adminCommission);
app.use('/addofflinework', addofflinework);
module.exports = app;
